
FROM python
RUN useradd -ms /bin/sh admin
COPY --chown=admin:admin . /scallshap
WORKDIR /scallshap
ENV -u username
ENV -p password
ENV PYTHONPATH "${PYTHONPATH}:./scallshap"
RUN pip install --upgrade build
RUN python -m build
RUN pip install twine
ENTRYPOINT ["twine"]

# RUN twine upload dist/* -u=$username -p=$password
