
FROM python
RUN useradd -ms /bin/sh admin
COPY --chown=admin:admin . /app
WORKDIR /app
ENV -u username
ENV -p password
RUN pip install twine
ENTRYPOINT ["twine"]

# RUN twine upload dist/* -u=$username -p=$password
