version: 2.1

orbs:
  python: circleci/python@1.5.0

workflows:
  main:  
    jobs:
      - build-and-test
jobs:
  build-and-test:  
    # Change the version below to your required version of python
    docker:
      - image: cimg/python:3.8
    # CircleCI will report the results back to your VCS provider.
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements_dev.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: |
            sudo apt-get update -y
            sudo apt-get install -y gnumeric
            cd data && curl -O 'https://archive.ics.uci.edu/ml/machine-learning-databases/00350/default%20of%20credit%20card%20clients.xls'
            ls -a
            ssconvert default%20of%20credit%20card%20clients.xls data.csv 
            sed -i '' 1d /home/circleci/project/data.csv
            ls -a
            # cd /home/circleci/project/tests/
            ls -a
            pytest 
            python -m main
